"""
Leave simulation module.

This module generates simulated employee leave request records
for the People Analytics Lakehouse Platform.

Each employee receives between 1 and 6 leave requests covering
the configured historical period.

Business logic:
- Leave cannot start before an employee's hire date.
- Leave duration is between 1 and 10 days.
- Leave requests can be either Approved or Pending.
- Approved requests have an approval date.
- Pending requests have no approval date (approved_date = None).
- Each leave request is associated with an approving manager.
"""

from __future__ import annotations

import random
from datetime import date, timedelta
from decimal import Decimal

from config.constants import DEFAULT_RANDOM_SEED, HISTORICAL_YEARS
from database.models import Employee, LeaveRequest


# -------------------------------------------------------------------
# Random seed
#
# Ensures reproducible simulated data when the simulator is rerun
# using the same seed.
# -------------------------------------------------------------------

random.seed(DEFAULT_RANDOM_SEED)


# -------------------------------------------------------------------
# Supported leave types
#
# These values represent the categories of leave that can be assigned
# to generated leave requests.
#
# These can later be loaded from:
#
# reference_data/leave_types.yml
#
# as part of the reusable reference-data framework.
# -------------------------------------------------------------------

LEAVE_TYPES = [
    "Annual Leave",
    "Sick Leave",
    "Parental Leave",
    "Compassionate Leave",
    "Study Leave",
]


def random_date_in_history() -> date:
    """
    Generate a random date within the configured historical period.

    The historical period is controlled by HISTORICAL_YEARS
    in config/constants.py.

    For example, if HISTORICAL_YEARS = 3, the generated date
    will fall somewhere between three years ago and today.

    Returns:
        date: A randomly generated historical date.
    """

    # Calculate the earliest possible historical date.
    start = date.today() - timedelta(
        days=365 * HISTORICAL_YEARS
    )

    # The latest possible date is today.
    end = date.today()

    # Select a random date between the start and end dates.
    return start + timedelta(
        days=random.randint(
            0,
            (end - start).days,
        )
    )


def generate_leave_requests(
    employees: list[Employee],
) -> list[LeaveRequest]:
    """
    Generate simulated leave requests for employees.

    Each employee receives between 1 and 6 leave requests.

    The generated LeaveRequest objects are returned to the simulation
    orchestrator, which is responsible for adding them to the SQLAlchemy
    session and committing them to PostgreSQL.

    Args:
        employees:
            List of Employee ORM objects generated by the employee
            simulator or retrieved from the database.

    Returns:
        list[LeaveRequest]:
            A list of generated LeaveRequest ORM objects.
    """

    # Container for all generated leave request records.
    records = []

    # -------------------------------------------------------------------
    # Identify managers
    #
    # Managers are required because each leave request contains an
    # approved_by_manager relationship.
    # -------------------------------------------------------------------

    managers = [
        employee
        for employee in employees
        if employee.is_manager
    ]

    # -------------------------------------------------------------------
    # Generate leave requests for every employee.
    # -------------------------------------------------------------------

    for employee in employees:

        # Each employee receives between 1 and 6 leave requests
        # across the historical simulation period.
        leave_count = random.randint(
            1,
            6,
        )

        for _ in range(leave_count):

            # -----------------------------------------------------------
            # Generate leave start date.
            #
            # max() ensures that the leave request cannot begin before
            # the employee joined the organisation.
            # -----------------------------------------------------------

            start_date = max(
                employee.hire_date,
                random_date_in_history(),
            )

            # -----------------------------------------------------------
            # Generate leave duration.
            #
            # Leave lasts between 1 and 10 calendar days.
            # -----------------------------------------------------------

            days = random.randint(
                1,
                10,
            )

            # Calculate the final day of leave.
            #
            # Subtracting one ensures that a one-day leave request has
            # the same start_date and end_date.
            end_date = start_date + timedelta(
                days=days - 1
            )

            # -----------------------------------------------------------
            # Determine the approving manager.
            #
            # Where the employee already has a manager relationship,
            # that manager is used.
            #
            # Otherwise, a manager is selected from the available
            # manager population.
            # -----------------------------------------------------------

            manager = (
                employee.manager
                or random.choice(managers)
            )

            # -----------------------------------------------------------
            # Generate leave request status.
            #
            # "Approved" appears twice to create a higher probability
            # of approved requests compared with pending requests.
            #
            # Approximate distribution:
            # - Approved: 66.7%
            # - Pending:  33.3%
            # -----------------------------------------------------------

            request_status = random.choice(
                [
                    "Approved",
                    "Approved",
                    "Pending",
                ]
            )

            # -----------------------------------------------------------
            # Generate approval date.
            #
            # Business rule:
            #
            # APPROVED REQUEST
            #     Must have an approved_date.
            #
            # PENDING REQUEST
            #     Has not yet been approved and therefore must have
            #     approved_date = None.
            #
            # SQLAlchemy will persist Python None as SQL NULL in
            # PostgreSQL.
            # -----------------------------------------------------------

            approved_date = (
                start_date
                - timedelta(
                    days=random.randint(
                        1,
                        6,
                    )
                )
                if request_status == "Approved"
                else None
            )

            # -----------------------------------------------------------
            # Create the LeaveRequest ORM object.
            # -----------------------------------------------------------

            leave_request = LeaveRequest(

                # Employee requesting the leave.
                employee=employee,

                # Randomly selected leave category.
                leave_type=random.choice(
                    LEAVE_TYPES
                ),

                # First day of leave.
                start_date=start_date,

                # Last day of leave.
                end_date=end_date,

                # Total number of leave days.
                number_of_days=Decimal(
                    days
                ),

                # Approved or Pending.
                request_status=request_status,

                # Simulate the employee submitting the request
                # between 7 and 30 days before the leave starts.
                requested_date=(
                    start_date
                    - timedelta(
                        days=random.randint(
                            7,
                            30,
                        )
                    )
                ),

                # Approved requests receive an approval date.
                #
                # Pending requests receive None, which becomes
                # NULL in PostgreSQL.
                approved_date=approved_date,

                # Manager responsible for approving the request.
                approved_by_manager=manager,

                # No free-text reason is generated at this stage.
                reason=None,
            )

            # Add the generated leave request to the output collection.
            records.append(
                leave_request
            )

    # Return all generated LeaveRequest ORM objects to the
    # simulation orchestrator.
    return records
