"""
Main data validation runner.

Validates the operational PostgreSQL data generated by the simulator.

This validation stage is intentionally separate from:

    quality.reference_data_checks
        Validates YAML reference data before database seeding.

    quality.raw_extraction_validation
        Validates PostgreSQL-to-Parquet extraction integrity.

Run from the project root:

    python -m quality.validation
"""

from __future__ import annotations

from dataclasses import dataclass

from config.logger import logger
from database.connection import get_session
from database.models import (
    Attendance,
    Employee,
    EmployeeExit,
    Payroll,
)

from quality.business_rules import (
    find_active_employees_with_exit_event,
    find_employees_with_negative_salary,
    find_employees_with_termination_before_hire,
    find_employees_without_manager,
    find_exit_date_mismatches,
    find_exit_events_before_hire_date,
    find_exit_events_with_non_terminated_status,
    find_exit_interviews_for_active_employees,
    find_negative_payroll_records,
    find_non_managers_without_manager,
    find_terminated_employees_without_exit_event,
)
from quality.duplicate_checks import (
    find_duplicate_emails,
    find_duplicate_employee_numbers,
)
from quality.effective_date_checks import (
    find_attendance_outside_employment,
    find_leave_outside_employment,
    find_manager_feedback_outside_employment,
    find_payroll_outside_employment,
    find_performance_reviews_outside_employment,
    find_promotions_outside_employment,
    find_surveys_outside_employment,
    find_training_outside_employment,
    find_transfers_outside_employment,
)
from quality.exceptions import DataQualityError
from quality.integrity_checks import (
    find_employees_with_missing_department,
    find_employees_with_missing_job_role,
    find_employees_with_missing_location,
    find_exit_interviews_without_exit_event,
    find_orphan_attendance_records,
    find_orphan_employee_exit_records,
    find_orphan_payroll_records,
)
from quality.metrics import get_table_counts
from quality.report import (
    export_csv,
    export_json,
)
from quality.validate_promotion_salary import (
    find_promotions_outside_new_role_salary_band,
    find_promotions_with_invalid_role_salary_band,
)
from quality.workforce_lifecycle_checks import (
    find_employee_promotion_state_mismatches,
    find_employee_transfer_state_mismatches,
    find_filled_recruitments_without_employee,
    find_open_recruitments_with_employee,
    find_recruitment_headcount_mismatch,
    find_recruitment_hire_date_mismatches,
)


# ---------------------------------------------------------------------------
# Result Model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ValidationResult:
    """
    Result returned by one operational data-quality check.
    """

    check_name: str
    passed: bool
    record_count: int
    severity: str


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def log_result(
    result: ValidationResult,
) -> None:
    """
    Log a validation result using severity-appropriate logging.
    """

    status = (
        "PASS"
        if result.passed
        else "FAIL"
    )

    message = (
        f"{status} | "
        f"{result.severity} | "
        f"{result.check_name} | "
        f"Records: {result.record_count}"
    )

    if result.passed:
        logger.info(
            message
        )

    elif result.severity == "CRITICAL":
        logger.error(
            message
        )

    else:
        logger.warning(
            message
        )


# ---------------------------------------------------------------------------
# Generic Validators
# ---------------------------------------------------------------------------

def validate_count_greater_than_zero(
    session,
    model,
    label: str,
) -> ValidationResult:
    """
    Confirm that an expected operational table contains records.
    """

    count = (
        session.query(model)
        .count()
    )

    return ValidationResult(
        check_name=(
            f"{label} count greater than zero"
        ),
        passed=count > 0,
        record_count=count,
        severity="CRITICAL",
    )


def validate_empty_result(
    check_name: str,
    records: list,
    severity: str,
) -> ValidationResult:
    """
    Convert a query returning invalid records into a validation result.

    A check passes when the supplied collection is empty.
    """

    return ValidationResult(
        check_name=check_name,
        passed=len(records) == 0,
        record_count=len(records),
        severity=severity,
    )


def validate_expected_single_top_manager(
    session,
) -> ValidationResult:
    """
    Confirm that exactly one employee has no manager.

    This represents the top-level employee in the simulated hierarchy.
    """

    employees_without_manager = (
        find_employees_without_manager(
            session
        )
    )

    return ValidationResult(
        check_name=(
            "Exactly one employee has no manager"
        ),
        passed=(
            len(employees_without_manager)
            == 1
        ),
        record_count=len(
            employees_without_manager
        ),
        severity="CRITICAL",
    )


# ---------------------------------------------------------------------------
# Table Counts
# ---------------------------------------------------------------------------

def print_table_counts(
    session,
) -> None:
    """
    Log row counts for all monitored operational tables.
    """

    logger.info(
        "=" * 60
    )

    logger.info(
        "TABLE COUNTS"
    )

    logger.info(
        "=" * 60
    )

    for (
        table_name,
        count,
    ) in get_table_counts(
        session
    ).items():

        logger.info(
            f"{table_name}: {count:,}"
        )


# ---------------------------------------------------------------------------
# Validation Runner
# ---------------------------------------------------------------------------

def run_validations(
) -> list[ValidationResult]:
    """
    Run all operational PostgreSQL data-quality checks.

    Returns:
        List of ValidationResult objects.

    Raises:
        DataQualityError:
            If one or more CRITICAL validations fail.
    """

    logger.info(
        "=" * 60
    )

    logger.info(
        "PEOPLE ANALYTICS DATA QUALITY VALIDATION"
    )

    logger.info(
        "=" * 60
    )

    session = get_session()

    results: list[
        ValidationResult
    ] = []

    try:
        # ---------------------------------------------------------------
        # Operational table counts
        # ---------------------------------------------------------------

        print_table_counts(
            session
        )

        # ---------------------------------------------------------------
        # Core dataset existence checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_count_greater_than_zero(
                    session,
                    Employee,
                    "Employees",
                ),
                validate_count_greater_than_zero(
                    session,
                    Attendance,
                    "Attendance",
                ),
                validate_count_greater_than_zero(
                    session,
                    Payroll,
                    "Payroll",
                ),
                validate_count_greater_than_zero(
                    session,
                    EmployeeExit,
                    "Employee exits",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Manager hierarchy checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_expected_single_top_manager(
                    session
                ),
                validate_empty_result(
                    (
                        "No non-manager employees "
                        "without manager"
                    ),
                    find_non_managers_without_manager(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Duplicate checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    "No duplicate employee numbers",
                    find_duplicate_employee_numbers(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    "No duplicate employee emails",
                    find_duplicate_emails(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Referential integrity checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    (
                        "No employees with "
                        "missing department"
                    ),
                    find_employees_with_missing_department(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No employees with "
                        "missing job role"
                    ),
                    find_employees_with_missing_job_role(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No employees with "
                        "missing location"
                    ),
                    find_employees_with_missing_location(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    "No orphan attendance records",
                    find_orphan_attendance_records(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    "No orphan payroll records",
                    find_orphan_payroll_records(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No orphan employee "
                        "exit records"
                    ),
                    find_orphan_employee_exit_records(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Financial and employee-state checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    (
                        "No employees with "
                        "negative salary"
                    ),
                    find_employees_with_negative_salary(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No employees with termination "
                        "before hire date"
                    ),
                    find_employees_with_termination_before_hire(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    "No negative payroll records",
                    find_negative_payroll_records(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Employee-exit lifecycle checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    (
                        "No active employees "
                        "with exit events"
                    ),
                    find_active_employees_with_exit_event(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No employee exit events "
                        "before hire date"
                    ),
                    find_exit_events_before_hire_date(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "Employee termination dates "
                        "match exit event dates"
                    ),
                    find_exit_date_mismatches(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "Exited employees have "
                        "terminated employment status"
                    ),
                    find_exit_events_with_non_terminated_status(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No terminated employees "
                        "without exit events"
                    ),
                    find_terminated_employees_without_exit_event(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No exit interviews without "
                        "employee exit events"
                    ),
                    find_exit_interviews_without_exit_event(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No exit interviews "
                        "for active employees"
                    ),
                    find_exit_interviews_for_active_employees(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Promotion salary checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    (
                        "No promotion salaries outside "
                        "new role salary band"
                    ),
                    find_promotions_outside_new_role_salary_band(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No promotions with invalid "
                        "new role salary band"
                    ),
                    find_promotions_with_invalid_role_salary_band(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Recruitment lifecycle checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    (
                        "No filled recruitment records "
                        "without successful employees"
                    ),
                    find_filled_recruitments_without_employee(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No open recruitment records "
                        "linked to employees"
                    ),
                    find_open_recruitments_with_employee(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "Successful recruits match "
                        "recruitment hire dates"
                    ),
                    find_recruitment_hire_date_mismatches(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "Employee count equals initial "
                        "workforce plus filled recruitments"
                    ),
                    find_recruitment_headcount_mismatch(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Current-state workforce checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    (
                        "Employee current role and salary "
                        "match latest promotion"
                    ),
                    find_employee_promotion_state_mismatches(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "Employee current department "
                        "location and manager match "
                        "latest transfer"
                    ),
                    find_employee_transfer_state_mismatches(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Effective-date checks
        # ---------------------------------------------------------------

        results.extend(
            [
                validate_empty_result(
                    (
                        "No attendance outside "
                        "employee employment window"
                    ),
                    find_attendance_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No payroll outside "
                        "employee employment window"
                    ),
                    find_payroll_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No leave outside "
                        "employee employment window"
                    ),
                    find_leave_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No training outside "
                        "employee employment window"
                    ),
                    find_training_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No performance reviews outside "
                        "employee employment window"
                    ),
                    find_performance_reviews_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No surveys outside "
                        "employee employment window"
                    ),
                    find_surveys_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No manager feedback outside "
                        "employee employment window"
                    ),
                    find_manager_feedback_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No promotions outside "
                        "employee employment window"
                    ),
                    find_promotions_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
                validate_empty_result(
                    (
                        "No transfers outside "
                        "employee employment window"
                    ),
                    find_transfers_outside_employment(
                        session
                    ),
                    "CRITICAL",
                ),
            ]
        )

        # ---------------------------------------------------------------
        # Log individual validation results
        # ---------------------------------------------------------------

        logger.info(
            "=" * 60
        )

        logger.info(
            "VALIDATION RESULTS"
        )

        logger.info(
            "=" * 60
        )

        for result in results:
            log_result(
                result
            )

        # ---------------------------------------------------------------
        # Export validation reports
        # ---------------------------------------------------------------

        export_csv(
            results
        )

        export_json(
            results
        )

        # ---------------------------------------------------------------
        # Summary metrics
        # ---------------------------------------------------------------

        passed_results = [
            result
            for result in results
            if result.passed
        ]

        failed_results = [
            result
            for result in results
            if not result.passed
        ]

        failed_critical = [
            result
            for result in failed_results
            if result.severity == "CRITICAL"
        ]

        logger.info(
            "=" * 60
        )

        logger.info(
            f"SUMMARY | "
            f"Total: {len(results)} | "
            f"Passed: {len(passed_results)} | "
            f"Failed: {len(failed_results)} | "
            f"Failed Critical: {len(failed_critical)}"
        )

        logger.info(
            "=" * 60
        )

        # ---------------------------------------------------------------
        # Quality gate
        # ---------------------------------------------------------------

        if failed_critical:
            failed_names = ", ".join(
                result.check_name
                for result in failed_critical
            )

            raise DataQualityError(
                "Operational data validation failed with "
                f"{len(failed_critical)} critical issue(s). "
                f"Failed checks: {failed_names}"
            )

        logger.info(
            "All critical operational data quality checks passed."
        )

        return results

    finally:
        session.close()


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    run_validations()
