"""Direct architecture-review regression evidence for G01–G04."""

from datetime import date
from dataclasses import replace
from unittest.mock import patch

from pyspark.sql import functions as F
from pyspark.sql.types import DateType, DecimalType, LongType, StringType

from spark.gold.attendance import normalize_attendance_source
from spark.gold.keys import assignment_key, movement_key, date_key
from spark.gold.reference import absence_domain, absence_domain_fingerprint
from spark.gold.validate import GoldValidationError
from spark.gold.workforce_history import _spark_key, build_dim_employee_assignment
from tests.spark.gold.dimension_fixtures import CoreDimensionTestCase, literal_frame
from tests.spark.gold import test_assignment_history as history


class CorrectiveGateTests(CoreDimensionTestCase):
    def setUp(self):
        history.Phase2SmokeTests.setUp(self)

    def assignments(self):
        return build_dim_employee_assignment(
            self.employees, self.promotions, self.transfers, self.exits, self.build
        )

    def test_g01_python_spark_key_parity(self):
        # Literal expected digests were independently calculated from the
        # documented UTF-8 byte-length frames, not regenerated by either helper.
        vectors = [
            (
                ("hr", "assignment", "1", "2024-01-01"),
                "fe951c07f95061030e313d5711013045fa55680c498a4f30ab98ecbc26dae8b9",
                "13e4816af93f4573c6af57705e4f83db260f25dc6f6e46ef14de3a2e7bdcd7bc",
            ),
            (
                ("hr:12|\u00e9", "assignment", "9223372036854775807", "2024-02-29"),
                "a663778f94e74ca4c17579d4db1de3260bb57e0f151396e78158dffa4cd89c5c",
                "54eca71d156cc54219a3c092a4a2aedacd752a9b756a23e6c1d22259e6b33e8a",
            ),
            (
                ("hr:12|\u00e9", "movement", "HIRE", "12"),
                "491388e1eee4ae0274ad7b83bcad4a3bbecd1950deb328b26b065801f3cde7d3",
                "5b81a4c73fcfcb6c472ceecdc91d749b21e26027cc1f7073bfe5e14c5f4aa570",
            ),
            (
                ("hr:12|\u00e9", "movement", "EXIT", "12"),
                "3b91a3f718fb004a70b6651cbdd9690d281df70ed68c889fede194bd93bb46a9",
                "3d577a7f8c6cd3126474c1f106df591dfcafce10a02d4a055653a27be08fdb9e",
            ),
            (
                ("hr:12|\u00e9", "movement", "PROMOTION", "12"),
                "20531bac394df327ce052956df42fd7982c3bf73d14b02437ee752966dc99ed7",
                "2fa63dcdca02cf22be9cfea6a1cd8d116bb051b0fa688f6ae6fa78897294b276",
            ),
            (
                ("hr:12|\u00e9", "movement", "TRANSFER", "12"),
                "767ae72174c02058809cb00e255e5c087cb41c425ef05c0492a509de3530f361",
                "9a43767667b2f6bccd8328b945d34d56867ba633442e6c56a1dbb61894f4848d",
            ),
        ]
        for (namespace, kind, first, second), old, expected in vectors:
            with self.subTest(kind=kind, identity=(first, second)):
                if kind == "assignment":
                    values = (int(first), date.fromisoformat(second))
                    canonical = assignment_key(namespace, *values)
                else:
                    values = (first, int(second))
                    canonical = movement_key(namespace, *values)
                actual = (
                    self.spark.range(1)
                    .select(
                        _spark_key(namespace, kind, *[F.lit(v) for v in values]).alias(
                            "k"
                        )
                    )
                    .first()
                    .k
                )
                self.assertEqual(canonical, expected)
                self.assertEqual(actual, expected)
                self.assertNotEqual(actual, old)

    def test_g01_null_identity_is_not_permitted_optional_date_is_unknown(self):
        self.assertEqual(date_key(None), 0)
        with self.assertRaises(ValueError):
            assignment_key("hr", 1, None)
        with self.assertRaises(ValueError):
            movement_key("hr", "HIRE", None)
        self.assertIsNone(
            self.spark.range(1)
            .select(_spark_key("hr", "assignment", F.lit(1), F.lit(None)).alias("k"))
            .first()
            .k
        )

    def test_g02_old_state_historical_evidence(self):
        self.promotions = self.promotions.withColumn(
            "old_role_id", F.lit(1).cast("long")
        )
        self.employees = self.employees.withColumn("role_id", F.lit(2).cast("long"))
        self.transfers = self.transfers.limit(0)
        row = (
            self.assignments()
            .filter("employee_key = 1")
            .orderBy("valid_from_date")
            .first()
        )
        self.assertEqual(row.job_role_key, 1)
        self.assertEqual(row.role_history_basis, "event-derived")

    def test_g03_same_day_hire_exit(self):
        self.promotions = self.promotions.limit(0)
        self.transfers = self.transfers.limit(0)
        self.employees = self.employees.withColumn(
            "hire_date",
            F.when(F.col("employee_id") == 2, F.col("termination_date")).otherwise(
                F.col("hire_date")
            ),
        )
        _, movements = history.Phase2SmokeTests.build_pair(self)
        rows = {
            r.movement_type: r for r in movements.filter("employee_key = 2").collect()
        }
        self.assertNotEqual(rows["EXIT"].before_assignment_key, "0")
        self.assertEqual(
            rows["EXIT"].before_assignment_key, rows["HIRE"].after_assignment_key
        )

    def test_g04_arbitrary_absence_narrative_rejected(self):
        source = literal_frame(
            self.spark,
            [
                ("attendance_id", LongType()),
                ("employee_id", LongType()),
                ("work_date", DateType()),
                ("status", StringType()),
                ("absence_reason", StringType()),
                ("hours_worked", DecimalType(18, 4)),
                ("overtime_hours", DecimalType(18, 4)),
            ],
            [
                (
                    1,
                    1,
                    date(2024, 1, 1),
                    "Absent",
                    "private narrative not a category",
                    "0",
                    "0",
                )
            ],
        )
        with self.assertRaises(GoldValidationError):
            normalize_attendance_source(source, self.build)

    def test_g02_transfer_old_state_all_attributes(self):
        self.transfers = self.transfers.withColumn(
            "old_manager_id", F.lit(2).cast("long")
        )
        rows = (
            self.assignments()
            .filter("employee_key = 1")
            .orderBy("valid_from_date")
            .collect()
        )
        self.assertEqual(
            (
                rows[0].department_key,
                rows[0].location_key,
                rows[0].manager_employee_key,
            ),
            (1, 1, 2),
        )
        self.assertEqual(
            (
                rows[0].department_history_basis,
                rows[0].location_history_basis,
                rows[0].manager_history_basis,
            ),
            ("event-derived",) * 3,
        )
        self.assertEqual(
            (
                rows[-1].department_key,
                rows[-1].location_key,
                rows[-1].manager_employee_key,
            ),
            (2, 2, 0),
        )

    def test_g02_contradictory_chain_evidence(self):
        for attribute, source_name, date_name, id_name, old_name in (
            ("role", "promotions", "promotion_date", "promotion_id", "old_role_id"),
            (
                "department",
                "transfers",
                "transfer_date",
                "transfer_id",
                "old_department_id",
            ),
            (
                "location",
                "transfers",
                "transfer_date",
                "transfer_id",
                "old_location_id",
            ),
            ("manager", "transfers", "transfer_date", "transfer_id", "old_manager_id"),
        ):
            with self.subTest(attribute=attribute):
                original = getattr(self, source_name)
                later = original.withColumn(
                    date_name, F.lit(date(2024, 2, 15))
                ).withColumn(id_name, F.lit(99).cast("long"))
                # Reconcile other attributes so the named contradiction is isolated.
                for field in original.columns:
                    if field.startswith("old_"):
                        later = later.withColumn(
                            field, F.col(field.replace("old_", "new_"))
                        )
                later = later.withColumn(old_name, F.lit(99).cast("long"))
                setattr(self, source_name, original.unionByName(later))
                with self.assertRaisesRegex(
                    GoldValidationError, "history_continuity_" + attribute
                ):
                    self.assignments()
                setattr(self, source_name, original)

    def test_g02_final_endpoint_reconciliation(self):
        for name, attribute in (
            ("role_id", "role"),
            ("department_id", "department"),
            ("location_id", "location"),
            ("manager_id", "manager"),
        ):
            with self.subTest(attribute=attribute):
                original = self.employees
                self.employees = original.withColumn(name, F.lit(1).cast("long"))
                with self.assertRaisesRegex(
                    GoldValidationError, "history_endpoint_" + attribute
                ):
                    self.assignments()
                self.employees = original

    def test_g02_hire_only_keeps_labelled_assumption(self):
        self.promotions, self.transfers = self.promotions.limit(
            0
        ), self.transfers.limit(0)
        row = self.assignments().filter("employee_key = 1").first()
        self.assertEqual(row.role_history_basis, "current-state-assumed")

    def test_g02_hire_date_event_precedence(self):
        # A later role change ensures current role differs from hire-day role.
        first = self.promotions.withColumn("promotion_date", F.lit(date(2023, 12, 31)))
        later = (
            self.promotions.withColumn("promotion_id", F.lit(11).cast("long"))
            .withColumn("old_role_id", F.lit(2).cast("long"))
            .withColumn("new_role_id", F.lit(1).cast("long"))
        )
        self.promotions = first.unionByName(later)
        self.employees = self.employees.withColumn("role_id", F.lit(1).cast("long"))
        row = (
            self.assignments()
            .filter("employee_key = 1")
            .orderBy("valid_from_date")
            .first()
        )
        self.assertEqual(row.job_role_key, 2)
        self.assertEqual(row.role_history_basis, "event-derived")

    def test_g02_hire_date_transfer_and_compatible_changes(self):
        self.promotions = self.promotions.withColumn(
            "promotion_date", F.lit(date(2023, 12, 31))
        )
        self.transfers = self.transfers.withColumn(
            "transfer_date", F.lit(date(2023, 12, 31))
        )
        row = self.assignments().filter("employee_key = 1").first()
        self.assertEqual(
            (row.department_key, row.location_key, row.job_role_key), (2, 2, 2)
        )
        self.assertEqual(
            (
                row.department_history_basis,
                row.location_history_basis,
                row.role_history_basis,
            ),
            ("event-derived",) * 3,
        )
        self.promotions = self.promotions.limit(0)
        row = self.assignments().filter("employee_key = 1").first()
        self.assertEqual(row.department_history_basis, "event-derived")

    def test_g02_hire_date_contradictory_old_evidence(self):
        self.promotions = self.promotions.withColumn(
            "promotion_date", F.lit(date(2023, 12, 31))
        )
        conflict = self.promotions.withColumn(
            "promotion_id", F.lit(99).cast("long")
        ).withColumn("old_role_id", F.lit(99).cast("long"))
        self.promotions = self.promotions.unionByName(conflict)
        with self.assertRaisesRegex(GoldValidationError, "same_day_conflict_old_role"):
            self.assignments()

    def test_g02_unavailable_old_evidence_remains_assumed(self):
        self.promotions = self.promotions.drop("old_role_id")
        row = (
            self.assignments()
            .filter("employee_key = 1")
            .orderBy("valid_from_date")
            .first()
        )
        self.assertEqual(row.role_history_basis, "current-state-assumed")
        self.assertEqual(row.job_role_key, 2)

    def test_g02_later_source_event_does_not_force_cutoff_endpoint(self):
        later = (
            self.promotions.withColumn("promotion_date", F.lit(date(2024, 4, 1)))
            .withColumn("promotion_id", F.lit(99).cast("long"))
            .withColumn("old_role_id", F.lit(2).cast("long"))
            .withColumn("new_role_id", F.lit(1).cast("long"))
        )
        self.promotions = self.promotions.unionByName(later)
        self.employees = self.employees.withColumn("role_id", F.lit(1).cast("long"))
        rows = (
            self.assignments()
            .filter("employee_key = 1")
            .orderBy("valid_from_date")
            .collect()
        )
        self.assertEqual(rows[-1].job_role_key, 2)
        self.assertEqual(rows[-1].valid_to_exclusive, date(2024, 3, 2))

    def test_g03_exit_date_assignment_boundary(self):
        self.transfers = self.transfers.withColumn(
            "employee_id", F.lit(2).cast("long")
        ).withColumn("transfer_date", F.lit(date(2024, 2, 29)))
        assignments, movements = history.Phase2SmokeTests.build_pair(self)
        final = (
            assignments.filter("employee_key = 2")
            .orderBy(F.col("valid_from_date").desc())
            .first()
        )
        event = movements.filter("movement_type = 'EXIT'").first()
        self.assertEqual(event.before_assignment_key, final.assignment_key)
        self.assertEqual(event.before_department_key, 2)
        self.assertEqual(event.after_assignment_key, "0")
        self.assertEqual(event.headcount_delta, -1)

    def test_g03_normal_exit_after_previous_changes(self):
        self.promotions = self.promotions.withColumn(
            "employee_id", F.lit(2).cast("long")
        ).withColumn("promotion_date", F.lit(date(2024, 2, 1)))
        self.transfers = self.transfers.withColumn(
            "employee_id", F.lit(2).cast("long")
        ).withColumn("transfer_date", F.lit(date(2024, 2, 15)))
        assignments, movements = history.Phase2SmokeTests.build_pair(self)
        final = (
            assignments.filter("employee_key = 2")
            .orderBy(F.col("valid_from_date").desc())
            .first()
        )
        event = movements.filter("movement_type = 'EXIT'").first()
        self.assertEqual(event.before_assignment_key, final.assignment_key)
        self.assertEqual(
            (event.before_job_role_key, event.before_department_key), (2, 2)
        )
        self.assertEqual((event.after_assignment_key, event.headcount_delta), ("0", -1))

    def attendance_source(self, status, reason):
        return literal_frame(
            self.spark,
            [
                ("attendance_id", LongType()),
                ("employee_id", LongType()),
                ("work_date", DateType()),
                ("status", StringType()),
                ("absence_reason", StringType()),
                ("hours_worked", DecimalType(18, 4)),
                ("overtime_hours", DecimalType(18, 4)),
            ],
            [(1, 1, date(2024, 1, 1), status, reason, "0", "0")],
        )

    def test_g04_every_governed_category_accepted(self):
        for reason in absence_domain():
            with self.subTest(reason=reason):
                self.assertEqual(
                    normalize_attendance_source(
                        self.attendance_source("Absent", reason), self.build
                    )
                    .first()
                    .absence_reason,
                    reason,
                )

    def test_g04_unknown_blank_null_malformed_rejected(self):
        for reason in (
            "Unknown category",
            "",
            "  ",
            None,
            " Medical Appointment",
            "Medical Appointment\n",
            "medical appointment",
        ):
            with self.subTest(reason=reason), self.assertRaises(GoldValidationError):
                normalize_attendance_source(
                    self.attendance_source("Absent", reason), self.build
                )
        with self.assertRaisesRegex(GoldValidationError, "attendance_source_schema"):
            normalize_attendance_source(
                self.attendance_source("Absent", "Medical Appointment").withColumn(
                    "absence_reason", F.lit(123)
                ),
                self.build,
            )

    def test_g04_non_absent_requires_null(self):
        for status in ("Present", "Remote", "Hybrid", "Training", "Business Travel"):
            with self.subTest(status=status):
                self.assertIsNone(
                    normalize_attendance_source(
                        self.attendance_source(status, None), self.build
                    )
                    .first()
                    .absence_reason
                )
                with self.assertRaises(GoldValidationError):
                    normalize_attendance_source(
                        self.attendance_source(status, "Medical Appointment"),
                        self.build,
                    )

    def test_g04_domain_change_changes_build_identity_and_stale_build_fails(self):
        changed = replace(self.build.spec, absence_domain_digest="b" * 64)
        self.assertNotEqual(self.build.spec.build_id, changed.build_id)
        with self.assertRaisesRegex(ValueError, "Governed absence domain"):
            changed.require_supported()
        with patch(
            "spark.gold.reference.absence_domain",
            return_value=(*absence_domain(), "New governed category"),
        ):
            self.assertNotEqual(
                self.build.spec.build_id,
                replace(
                    self.build.spec,
                    absence_domain_digest=absence_domain_fingerprint(),
                ).build_id,
            )
            with self.assertRaisesRegex(ValueError, "Governed absence domain"):
                normalize_attendance_source(
                    self.attendance_source("Absent", "Medical Appointment"), self.build
                )
